### ISSUE TITLE
Erroneous attempt to delete old log file?

### ISSUE THREAD

**Issue by assafcarlsbad** [yeggor/UEFI_RETool#11]
Inside the `analyse_all` function we can find the following snippet which tries to delete the previous log file:

```python
log_path = os.path.join('log', 'ida_' + scr_name.replace('.py', '.log'))
if os.path.isfile(log_path):
	os.remove(log_path)
```

However, IMHO the output emitted by the analyzer script is a Markdown file with an `.md` extension, which means the above code will never execute. Am I missing something?

**Comment by yeggor** [comment]
You are right, thanks, I fixed it
