### ISSUE TITLE
Support UEFI runtime services in addition to boot services

### ISSUE THREAD

**Issue by assafcarlsbad** [yeggor/UEFI_RETool#15]
Currently the IDA plugin does a very good job in finding calls to several selected UEFI boot services, but so far the runtime services were neglected. Since runtime services are a key part of the UEFI specification, supporting them will greatly aid the reverse engineering of virtually any UEFI module.

**Comment by yeggor** [comment]
This plugin is partially rewritten in C++ (https://github.com/binarly-io/efiXplorer) and has a primitive search for runtime services via gRT. This does not work for all drivers, but we are working on a more advanced search. Any ideas, problems and pull requests are welcome.
