### ISSUE TITLE
IDA Pro: search protocols

### ISSUE THREAD

**Issue by krsh** [yeggor/UEFI_RETool#16]
A question:
in **IDA Pro**, why did you choose 25 (x86) and 16 (x64) when looking for protocols?
In `get_protocols()` (https://github.com/yeggor/UEFI_RETool/blob/master/ida_plugin/uefi_analyser/analyser.py#L130):

```python
            for address in self.gBServices[service_name]:
                ea, found = address, False
                if self.arch == 'x86':
                    for _ in range(1, 25):
                        ea = idc.prev_head(ea)
                        if (idc.get_operand_value(ea, 0) > self.base
                                and idc.print_insn_mnem(ea) == 'push'):
                            found = True
                            break
                if self.arch == 'x64':
                    for _ in range(1, 16):
                        ea = idc.prev_head(ea)
                        if (idc.get_operand_value(ea, 1) > self.base
                                and idc.print_insn_mnem(ea) == 'lea'):
                            found = True
                            break
```

In **radare2**, instead, you use LEA_NUM (x64), a kind of instruction offset. This solution, unfortunately, is not always accurate.

What is the correct solution?

**Comment by yeggor** [comment]
25 and 16 were chosen to cover some of the edge cases I've encountered in practice.
I originally used the same approach with lea, and it should work correctly with 64-bit drivers. But with 32-bit it is a little more complicated, there argements are transmitted in a different way.

Now all this code has been rewritten in `c++` (https://github.com/binarly-io/efiXplorer/blob/master/src/efiAnalysis.cpp), it works for both 64-bit and 32-bit images. I would advise you to focus on it, as it works better and has experimental measurements.

**Comment by krsh** [comment]
Thank you. 
Do you know if there is an _efiXplorer_ implementation that uses **radare2** instead of **Ida Pro**? (@trufae)

**Comment by trufae** [comment]
Nope i dont know any. Despite i wrote some scripts for analyzing uefis in the past with r2. Maybe @xvilka knows more about this
