### ISSUE TITLE
How can I use this tool？

### ISSUE THREAD

**Issue by zhjygit** [yeggor/UEFI_RETool#17]
Overall, I don't see the significance of this tool, and it feels like it's useless compared to uefitools. Are there any other test cases or usage methods, thank you.

**Comment by yeggor** [comment]
This tool has nothing to do with UEFITool. UEFITool is developed for parsing and visualising the UEFI firmware image. And this tool is developed to help with static analysis of modules that are part of the firmware (and it require IDA Pro as an analysis backend).
In addition, this tool is outdated in it current form. The much better quality of analysis can be achieved with [efiXplorer](https://github.com/binarly-io/efixplorer).

**Comment by zhjygit** [comment]
Thank a lot.
