### ISSUE TITLE
strange representation guids

### ISSUE THREAD

**Issue by Raven19409** [yeggor/UEFI_RETool#6]
why?
data:00000000000E2280 ; EFI_GUID *gEfiLoadedImageProtocolGuid_0xe2280
.data:00000000000E2280 gEfiLoadedImageProtocolGuid_0xe2280 dq 11D295625B1B31A1h
.data:00000000000E2280                                         ; DATA XREF: sub_1CD7E+1D5↑o
.data:00000000000E2280                                         ; sub_1D0C6+111↑o ...
.data:00000000000E2288                 db  8Eh ; Ћ
.data:00000000000E2289                 db  3Fh ; ?
.data:00000000000E228A                 db    0
.data:00000000000E228B                 db 0A0h ;  
.data:00000000000E228C                 db 0C9h ; Й
.data:00000000000E228D                 db  69h ; i
.data:00000000000E228E                 db  72h ; r
.data:00000000000E228F                 db  3Bh ; ;

but  corectly

.data:00000000000E2280 ; EFI_GUID *gEfiLoadedImageProtocolGuid_0xe2280
.data:00000000000E2280 gEfiLoadedImageProtocolGuid_0xe2280 DGUID {5B1B31A1-9562-11D2-8E3F-00A0C969723B}
.data:00000000000E2280                                         ; DATA XREF: sub_1CD7E+1D5↑o
.data:00000000000E2280                                         ; sub_1D0C6+111↑o ...
.data:00000000000E2280                                         ; ->EFI_LOADED_IMAGE_PROTOCOL_GUID

**Comment by yeggor** [comment]
Thanks, now I'm [bring GUIDs to the EFI_GUID structure](https://github.com/yeggor/UEFI_RETool/commit/b7229d046b8cc981fe1a21ccdc307b699c37debe):
```
.data:00000000000E21F0 ; EFI_GUID *EFI_FILE_SYSTEM_INFO_ID_GUID_0xe21f0
.data:00000000000E21F0 EFI_FILE_SYSTEM_INFO_ID_GUID_0xe21f0 dd 9576E93h             ; Data1
.data:00000000000E21F0                                         ; DATA XREF: sub_1D29D+F↑o
.data:00000000000E21F0                                         ; sub_1D29D+5B↑o ...
.data:00000000000E21F0                 dw 6D3Fh                ; Data2
.data:00000000000E21F0                 dw 11D2h                ; Data3
.data:00000000000E21F0                 db 8Eh, 39h, 0, 0A0h, 0C9h, 69h, 72h, 3Bh; Data4
.data:00000000000E2200 ; EFI_GUID *gEfiFileInfoGuid_0xe2200
.data:00000000000E2200 gEfiFileInfoGuid_0xe2200 dd 9576E92h             ; Data1
.data:00000000000E2200                                         ; DATA XREF: sub_1D4EB+3B5↑o
.data:00000000000E2200                                         ; sub_1D4EB+3F5↑o ...
.data:00000000000E2200                 dw 6D3Fh                ; Data2
.data:00000000000E2200                 dw 11D2h                ; Data3
.data:00000000000E2200                 db 8Eh, 39h, 0, 0A0h, 0C9h, 69h, 72h, 3Bh; Data4
.data:00000000000E2210 ; EFI_GUID *gEfiSimpleNetworkProtocolGuid_0xe2210
.data:00000000000E2210 gEfiSimpleNetworkProtocolGuid_0xe2210 dd 0A19832B9h           ; Data1
.data:00000000000E2210                                         ; DATA XREF: sub_1F7B5+402↑o
.data:00000000000E2210                                         ; sub_1F7B5+5CD↑o ...
.data:00000000000E2210                 dw 0AC25h               ; Data2
.data:00000000000E2210                 dw 11D3h                ; Data3
.data:00000000000E2210                 db 9Ah, 2Dh, 0, 90h, 27h, 3Fh, 0C1h, 4Dh; Data4
.data:00000000000E2220 ; EFI_GUID *gEfiSimpleFileSystemProtocolGuid_0xe2220
.data:00000000000E2220 gEfiSimpleFileSystemProtocolGuid_0xe2220 dd 964E5B22h            ; Data1
.data:00000000000E2220                                         ; DATA XREF: sub_1D4EB+BD↑o
.data:00000000000E2220                                         ; sub_1D4EB+13A↑o ...
.data:00000000000E2220                 dw 6459h                ; Data2
.data:00000000000E2220                 dw 11D2h                ; Data3
.data:00000000000E2220                 db 8Eh, 39h, 0, 0A0h, 0C9h, 69h, 72h, 3Bh; Data4
```
If you like another representation, change this [file](https://github.com/yeggor/UEFI_RETool/blob/master/ida_plugin/uefi_analyser/analyser.py).
